# Generated by Django 4.0.4 on 2022-07-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
