# Generated by Django 4.0.4 on 2022-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time',
            field=models.CharField(default='5 days', max_length=100),
        ),
    ]
