# Generated by Django 4.0.4 on 2022-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_destination_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_detail',
            name='days',
            field=models.TextField(blank=True),
        ),
    ]
