# Generated by Django 4.0.5 on 2022-07-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_contactdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
