# Generated by Django 4.0.5 on 2022-07-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passwrord',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
