# Generated by Django 4.0.4 on 2022-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_destination_detail_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_name_alias',
            field=models.CharField(default='', max_length=100),
        ),
    ]
