# Generated by Django 4.0.5 on 2022-07-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_rename_customer_customerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_id',
        ),
    ]
