# Generated by Django 4.0.5 on 2022-07-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_customer_passwrord_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passwrord',
            new_name='password',
        ),
    ]
