# Generated by Django 4.0.5 on 2022-07-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_rename_passwrord_customer_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactDetails',
        ),
    ]
