# Generated by Django 4.0.5 on 2022-07-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_rename_contact_contactdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
