# Generated by Django 4.0.4 on 2022-08-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0004_invoicedetail_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
    ]
